name: freqtrade bots test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Freqtrade
      run: |
        git clone -b develop --depth 1 https://github.com/freqtrade/freqtrade.git
        cd freqtrade
        ./setup.sh -i
        pip install -e .

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Run tests
      run: |
        source freqtrade/.venv/bin/activate
#        TODO: Implement / fix run tests job, pytest isn't able to find modules in freqtrade venv
        freqtrade -h
        
