name: freqtrade bots test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Freqtrade
      run: |
        git clone -b develop --depth 1 https://github.com/freqtrade/freqtrade.git
        cd freqtrade
        ./setup.sh -i

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r freqtrade/requirements.txt
        pip install -r freqtrade/requirements-test.txt  # Install test dependencies


    - name: Run tests
      run: |
        pytest tests/
        
